<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Inventory;
use App\Models\Supplier;

class InventorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $suppliers = Supplier::all();
        
        $inventoryItems = [
            // Fresh Produce
            [
                'name' => 'Fresh Tomatoes',
                'sku' => 'PROD-001',
                'category' => 'Fresh Produce',
                'unit' => 'kg',
                'current_stock' => 25.5,
                'min_stock' => 10.0,
                'max_stock' => 50.0,
                'cost_per_unit' => 2.50,
                'supplier_id' => $suppliers->where('name', 'Fresh Foods Co.')->first()->id,
                'location' => 'Refrigerator A',
                'description' => 'Fresh vine-ripened tomatoes',
                'is_active' => true,
                'expiry_date' => now()->addDays(7),
                'notes' => 'Store in refrigerator, use within 7 days',
            ],
            [
                'name' => 'Lettuce',
                'sku' => 'PROD-002',
                'category' => 'Fresh Produce',
                'unit' => 'kg',
                'current_stock' => 15.0,
                'min_stock' => 5.0,
                'max_stock' => 30.0,
                'cost_per_unit' => 1.80,
                'supplier_id' => $suppliers->where('name', 'Fresh Foods Co.')->first()->id,
                'location' => 'Refrigerator A',
                'description' => 'Fresh iceberg lettuce',
                'is_active' => true,
                'expiry_date' => now()->addDays(5),
                'notes' => 'Keep refrigerated, wash before use',
            ],
            [
                'name' => 'Onions',
                'sku' => 'PROD-003',
                'category' => 'Fresh Produce',
                'unit' => 'kg',
                'current_stock' => 40.0,
                'min_stock' => 15.0,
                'max_stock' => 80.0,
                'cost_per_unit' => 1.20,
                'supplier_id' => $suppliers->where('name', 'Fresh Foods Co.')->first()->id,
                'location' => 'Dry Storage',
                'description' => 'Yellow onions',
                'is_active' => true,
                'expiry_date' => now()->addDays(30),
                'notes' => 'Store in cool, dry place',
            ],

            // Meat Products
            [
                'name' => 'Beef Ground',
                'sku' => 'MEAT-001',
                'category' => 'Meat',
                'unit' => 'kg',
                'current_stock' => 30.0,
                'min_stock' => 10.0,
                'max_stock' => 60.0,
                'cost_per_unit' => 12.50,
                'supplier_id' => $suppliers->where('name', 'Quality Meats Ltd.')->first()->id,
                'location' => 'Freezer A',
                'description' => 'Premium ground beef 80/20',
                'is_active' => true,
                'expiry_date' => now()->addDays(90),
                'notes' => 'Keep frozen, thaw in refrigerator',
            ],
            [
                'name' => 'Chicken Breast',
                'sku' => 'MEAT-002',
                'category' => 'Meat',
                'unit' => 'kg',
                'current_stock' => 25.0,
                'min_stock' => 8.0,
                'max_stock' => 50.0,
                'cost_per_unit' => 8.75,
                'supplier_id' => $suppliers->where('name', 'Quality Meats Ltd.')->first()->id,
                'location' => 'Freezer B',
                'description' => 'Boneless skinless chicken breast',
                'is_active' => true,
                'expiry_date' => now()->addDays(90),
                'notes' => 'Keep frozen, thaw in refrigerator',
            ],
            [
                'name' => 'Pork Chops',
                'sku' => 'MEAT-003',
                'category' => 'Meat',
                'unit' => 'kg',
                'current_stock' => 18.0,
                'min_stock' => 6.0,
                'max_stock' => 35.0,
                'cost_per_unit' => 9.25,
                'supplier_id' => $suppliers->where('name', 'Quality Meats Ltd.')->first()->id,
                'location' => 'Freezer A',
                'description' => 'Center-cut pork chops',
                'is_active' => true,
                'expiry_date' => now()->addDays(90),
                'notes' => 'Keep frozen, thaw in refrigerator',
            ],

            // Seafood
            [
                'name' => 'Salmon Fillets',
                'sku' => 'FISH-001',
                'category' => 'Seafood',
                'unit' => 'kg',
                'current_stock' => 12.0,
                'min_stock' => 4.0,
                'max_stock' => 25.0,
                'cost_per_unit' => 18.50,
                'supplier_id' => $suppliers->where('name', 'Ocean Seafood Supply')->first()->id,
                'location' => 'Freezer C',
                'description' => 'Atlantic salmon fillets',
                'is_active' => true,
                'expiry_date' => now()->addDays(60),
                'notes' => 'Keep frozen, thaw in refrigerator',
            ],
            [
                'name' => 'Shrimp',
                'sku' => 'FISH-002',
                'category' => 'Seafood',
                'unit' => 'kg',
                'current_stock' => 8.0,
                'min_stock' => 3.0,
                'max_stock' => 20.0,
                'cost_per_unit' => 22.00,
                'supplier_id' => $suppliers->where('name', 'Ocean Seafood Supply')->first()->id,
                'location' => 'Freezer C',
                'description' => 'Large peeled shrimp',
                'is_active' => true,
                'expiry_date' => now()->addDays(60),
                'notes' => 'Keep frozen, thaw in refrigerator',
            ],

            // Dairy
            [
                'name' => 'Milk',
                'sku' => 'DAIRY-001',
                'category' => 'Dairy',
                'unit' => 'L',
                'current_stock' => 20.0,
                'min_stock' => 5.0,
                'max_stock' => 40.0,
                'cost_per_unit' => 1.25,
                'supplier_id' => $suppliers->where('name', 'Fresh Foods Co.')->first()->id,
                'location' => 'Refrigerator B',
                'description' => 'Whole milk 3.25%',
                'is_active' => true,
                'expiry_date' => now()->addDays(7),
                'notes' => 'Keep refrigerated, check expiry date',
            ],
            [
                'name' => 'Cheese Cheddar',
                'sku' => 'DAIRY-002',
                'category' => 'Dairy',
                'unit' => 'kg',
                'current_stock' => 10.0,
                'min_stock' => 3.0,
                'max_stock' => 20.0,
                'cost_per_unit' => 6.50,
                'supplier_id' => $suppliers->where('name', 'Fresh Foods Co.')->first()->id,
                'location' => 'Refrigerator B',
                'description' => 'Sharp cheddar cheese',
                'is_active' => true,
                'expiry_date' => now()->addDays(21),
                'notes' => 'Keep refrigerated, wrap tightly',
            ],

            // Pantry Items
            [
                'name' => 'Flour All-Purpose',
                'sku' => 'PANTRY-001',
                'category' => 'Pantry',
                'unit' => 'kg',
                'current_stock' => 50.0,
                'min_stock' => 15.0,
                'max_stock' => 100.0,
                'cost_per_unit' => 1.80,
                'supplier_id' => $suppliers->where('name', 'Bakery Essentials')->first()->id,
                'location' => 'Dry Storage',
                'description' => 'All-purpose flour',
                'is_active' => true,
                'expiry_date' => now()->addDays(365),
                'notes' => 'Store in cool, dry place',
            ],
            [
                'name' => 'Olive Oil',
                'sku' => 'PANTRY-002',
                'category' => 'Pantry',
                'unit' => 'L',
                'current_stock' => 15.0,
                'min_stock' => 5.0,
                'max_stock' => 30.0,
                'cost_per_unit' => 8.50,
                'supplier_id' => $suppliers->where('name', 'Bakery Essentials')->first()->id,
                'location' => 'Dry Storage',
                'description' => 'Extra virgin olive oil',
                'is_active' => true,
                'expiry_date' => now()->addDays(730),
                'notes' => 'Store in cool, dark place',
            ],
            [
                'name' => 'Pasta Spaghetti',
                'sku' => 'PANTRY-003',
                'category' => 'Pantry',
                'unit' => 'kg',
                'current_stock' => 30.0,
                'min_stock' => 10.0,
                'max_stock' => 60.0,
                'cost_per_unit' => 2.25,
                'supplier_id' => $suppliers->where('name', 'Bakery Essentials')->first()->id,
                'location' => 'Dry Storage',
                'description' => 'Spaghetti pasta',
                'is_active' => true,
                'expiry_date' => now()->addDays(730),
                'notes' => 'Store in cool, dry place',
            ],

            // Beverages
            [
                'name' => 'Soft Drinks',
                'sku' => 'BEV-001',
                'category' => 'Beverages',
                'unit' => 'cans',
                'current_stock' => 200.0,
                'min_stock' => 50.0,
                'max_stock' => 400.0,
                'cost_per_unit' => 0.75,
                'supplier_id' => $suppliers->where('name', 'Beverage Solutions')->first()->id,
                'location' => 'Beverage Storage',
                'description' => 'Assorted soft drinks',
                'is_active' => true,
                'expiry_date' => now()->addDays(180),
                'notes' => 'Store in cool place',
            ],
            [
                'name' => 'Bottled Water',
                'sku' => 'BEV-002',
                'category' => 'Beverages',
                'unit' => 'bottles',
                'current_stock' => 150.0,
                'min_stock' => 30.0,
                'max_stock' => 300.0,
                'cost_per_unit' => 0.50,
                'supplier_id' => $suppliers->where('name', 'Beverage Solutions')->first()->id,
                'location' => 'Beverage Storage',
                'description' => 'Spring water bottles',
                'is_active' => true,
                'expiry_date' => now()->addDays(365),
                'notes' => 'Store in cool place',
            ],
        ];

        foreach ($inventoryItems as $item) {
            Inventory::create($item);
        }
    }
} 